// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufcgacjszenkfxqditqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmY2dhY2pzemVua2Z4cWRpdHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MzE2OTAsImV4cCI6MjA2NjEwNzY5MH0.cmT9D_ZGcSck1S1kg31yvifs1I2Q3r2mdG1PJmPFzFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);